### ISSUE TITLE
Parser Failed

### ISSUE THREAD

**Issue by VonZorch** [phobos2077/sfall_script_editor#1]
Every time I make any change to a script, even a simple blank line, the parser shows a parsing failed until after I look at another file.  This happens running on Windows 8 and Wine 1.8 on Linux Mint 17.3.

**Comment by VonZorch** [comment]
Never mind, it turned out to be an issue with the script I decompiled to make changes to.

**Comment by phobos2077** [comment]
Yeah, the parser is still tend to just fail very often despite many improvements. At least I think it should remember preprocessor macros in such cases.
