### ISSUE TITLE
InventoryMove problem

### ISSUE THREAD

**Issue by VonZorch** [phobos2077/sfall_script_editor#2]
I'm trying to use the inventorymove hook in a script.  It return the correct slot but item numbers are semi-random 7 or occasionaly 6 digit numbers.  The number doesn't change while a game is running, but does on each game load.
The first 4 (leftmost) digits are always the same during each game.  For instance every item number will be 6958xx or 6958xxx.
Is this a bug?  If not, how do I convert this number into a proper item PID?
Also, is there some way to get the actual hit number the game generates?  Not the hit chance, that's easy, but the, for want of a better term, actual die roll.  Or alternately the amount the roll was made or missed by.

**Comment by VonZorch** [comment]
This is on Windows 8.1 and Wine 1.8 as XP, using sfall 3.6, 3.7 and 3.7a.

**Comment by phobos2077** [comment]
Number is an object pointer. Try
`obj_pid(item)`

What do you mean by "hit number"? Have you tried this:

```
hs_afterhitroll.int

Runs after fallout has decided if an attack will hit or miss

int     arg1 - If the attack will hit. (0 - critical miss, 1 - miss, 2 - hit, 3 - critical hit)
critter arg2 - The attacker
critter arg3 - The target of the attack
int     arg4 - The bodypart
int     arg5 - The hit chance

int     ret1 - Override the hit/miss
int     ret2 - Override the targeted bodypart
critter ret3 - Override the target of the attack
```

PS: this issue is related to sfall, not the Script Editor :)

**Comment by VonZorch** [comment]
Grazi Sahib.

**Comment by VonZorch** [comment]
About the hit number it is the random number generated by the game engine that is compared to the hit chance to see if an attack hits or not.
Yes I did try hs_afterhitroll and even found the commands I need to use.  Which brings up another issue.  The command how_much(val), which is what I need to return the value, always fails the parser and compiler.  if its something like (3+how_much(val)); then it gives an error  of missing ')' it its like this how_much(val); the error is expecting';', if it's in a display_msg such as display_msg("Result="+how_much); it displays nothing not even the string literal, in the form how_much, it parses and compiles but acts like a zero.
Is there somewhere other than here to put in feature requests?
