### ISSUE TITLE
Ошибка в препроцессоре компилятора compile.exe.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall_script_editor#3]
Если в макросе имеется обратная косая черта `\`  с символом конца команды `;` 
то в случае если после косой черты будут стоять лишние пробелы, препроцессор это будет воспринимать как ошибку.
`attack(source_obj);                           \__`  - пробелы подчеркнуты

**Comment by phobos2077** [comment]
Это известная особенность препроцессора. Любой пробел после косой черты считается ошибкой, т.к. препроцессор ищет последовательность двух символов - бекслеш и перенос строки.
Не уверен что это вообще можно назвать ошибкой, т.к. если воспринимать слеш посреди строки как перенос - могут возникнуть проблемы с самим кодом.

Например тут написано про Backslash-newline: https://gcc.gnu.org/onlinedocs/gcc-2.95.3/cpp_1.html

**Comment by FakelsHub** [comment]
Препроцессор WCC386 такое сочетание не считает ошибкой.

**Comment by phobos2077** [comment]
Компилятор без изменений использует библиотеку mcpp для препроцессинга: http://mcpp.sourceforge.net/

**Comment by FakelsHub** [comment]
Что же сразу не сказал, что это не к вам претензия)
Тогда  получается что использование препроцессора от Watcom в этом плане по лучше будет.

**Comment by NovaRain** [comment]
Why not add an option to automatically trim trailing spaces on saving for the script editor?

**Comment by FakelsHub** [comment]
> Why not add an option to automatically trim trailing spaces on saving for the script editor?

Possible)
But the files headers from the project Fallout: Nevada, there everywhere stumble spaces after Backslash, and propagates and manually correct as you do not want.
People complain about not able to compile the source script code.
I think that will add to the ScriptEditor the possibility of using the Watcom preprocessor.

```
Но это файлы headers из проекта Fallout: Nevada, там повсеместно натыкали пробелов после Backslash, а пробегаться и вручную исправлять как то не хочется.
Да и люди жалуются на не возможность скомпилировать исходник.
Я думаю что добавлю в ScriptEditor возможность использования Watcom препроцессора.
```

**Comment by NovaRain** [comment]
Well, I always trim trailing spaces in scripts/headers, as most of text editors can do it easily. Trailing spaces only bring troubles in my book.
I remembered the Watcom preprocessor used by official script compiler is pretty outdated. Personally I couldn't see a point reverting back to old preprocessor other than letting people keep those trailing spaces for no good reason.

**Comment by phobos2077** [comment]
@FakelsHub  не страдай ерундой, просто удали все пробелы в исходниках Невады одним разом (можно сделать через редактор типа Notepad++ или Sublime - через поиск и замену по регулярке) и забудь об этом.
Используя устаревший препроцессор ты только огребешь больше проблем.

**Comment by FakelsHub** [comment]
Да не нужны мне исходники невады, мне человек написал что sfall script editor не компилирует их.
Ну не знаю какие там проблемы могут возникнуть, всегда использовал watcom в качестве препроцессинга и не замечал никаких проблем с ним.

**Comment by phobos2077** [comment]
Тогда просто ответь этому человеку чтобы удалил пробелы и не мучился :)
Таков препроцессор и менять его ради небольшого дополнительного удобства не вижу смысла.

**Comment by FakelsHub** [comment]
> Тогда просто ответь этому человеку чтобы удалил пробелы и не мучился :)

да я ему написал что это глюк сфаловсого препроцессора))
и человек там не особо опытен в эти делах чтобы по заголовкам лазить.

>Таков препроцессор и менять его ради небольшого дополнительного удобства не вижу смысла.

Так никто и не меняет mcpp на wcc, а дополняет возможность его использование в случае чего,
я уже его включил в редактор.
И еще вопросец через compiler.exe как я понял нельзя передавать параметры для препроцессора mcpp, кроме тех которые предусмотрены, да?
Есть одна нужная опция, не знаю как сформулировать правильно, в общем передавать препроцессору константу для директив условной компиляции #if
в wcc это опция -d< id > [=text] precompilation #define <id> [text]
в mcpp перечитал мануал по его использованию и не нашел такой функции, если в курсе то подскажите.
