### ISSUE TITLE
Script Editor Crashes Under Wine.

### ISSUE THREAD

**Issue by VonZorch** [phobos2077/sfall_script_editor#4]
I'm using 4.0.5 and it crashes when I try to compile a script with a "pipe not connected" error.
Any recommendation about which version of Windows to run it under, and what version of .NET needs to be installed?
I currently  am using XP with .NET 2.0.

**Comment by NovaRain** [comment]
The script editor itself should run on .NET framework 2.0~3.5. The compiler/parser are built with VS2010 and can only run on XP SP2 or higher.

**Comment by VonZorch** [comment]
Thanks, that helps.
